// rates.js - 祐誠/駿甫區專屬佣金數據庫 (2026/02/03 更新)
window.PRODUCT_RATES = [
  // --- 1. 利變型壽險 (LIFE) ---
  { code: 'AYWTPL', term: '6', minAge: 0, maxAge: 65, fycRate: 15, marketingRate: 2, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8467' },
  { code: 'AYWTPL', term: '10', minAge: 0, maxAge: 65, fycRate: 20, marketingRate: 5, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8467' },
  { code: 'AYWTPL', term: '20', minAge: 0, maxAge: 60, fycRate: 30, marketingRate: 10, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8467' },
  { code: 'AYWUPL', term: '6', minAge: 0, maxAge: 74, fycRate: 15, marketingRate: 2, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8468' },
  { code: 'AYWUPL', term: '10', minAge: 0, maxAge: 70, fycRate: 20, marketingRate: 5, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8468' },
  { code: 'AYWUPL', term: '20', minAge: 0, maxAge: 60, fycRate: 30, marketingRate: 10, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8468' },
  { code: 'AEHUPL', term: '6', minAge: 0, maxAge: 74, fycRate: 15, marketingRate: 2, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8036' },
  { code: 'AEHUPL', term: '10', minAge: 0, maxAge: 70, fycRate: 20, marketingRate: 5, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8036' },
  { code: 'AEHUPL', term: '20', minAge: 0, maxAge: 60, fycRate: 30, marketingRate: 10, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8036' },
  { code: 'ALHUPL', term: '6', minAge: 0, maxAge: 65, fycRate: 15, marketingRate: 2, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8882' },
  { code: 'ALHUPL', term: '10', minAge: 0, maxAge: 65, fycRate: 20, marketingRate: 5, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8882' },
  { code: 'ALHUPL', term: '20', minAge: 0, maxAge: 55, fycRate: 30, marketingRate: 10, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8882' },
  { code: 'ARTE', term: '2', minAge: 0, maxAge: 61, fycRate: 4, marketingRate: 2, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8881' },
  { code: 'ARTE', term: '6', minAge: 0, maxAge: 59, fycRate: 10, marketingRate: 3, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8881' },
  { code: 'ARTE', term: '10', minAge: 0, maxAge: 55, fycRate: 13, marketingRate: 7, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8881' },
  { code: 'ARTE', term: '15', minAge: 0, maxAge: 50, fycRate: 16, marketingRate: 9, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8881' },
  { code: 'ARUE2', term: '2', minAge: 0, maxAge: 61, fycRate: 4, marketingRate: 2, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/7643' },
  { code: 'ARUE2', term: '6', minAge: 0, maxAge: 59, fycRate: 10, marketingRate: 3, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/7643' },
  { code: 'ARUE2', term: '10', minAge: 0, maxAge: 55, fycRate: 13, marketingRate: 7, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/7643' },
  { code: 'ARUE2', term: '15', minAge: 0, maxAge: 50, fycRate: 16, marketingRate: 9, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/7643' },
  { code: '3ATE', term: '3', minAge: 0, maxAge: 65, fycRate: 5, marketingRate: 0, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/9778' },
  { code: 'NATE', term: '6', minAge: 0, maxAge: 65, fycRate: 10, marketingRate: 0, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8564' },
  { code: 'NATE', term: '10', minAge: 0, maxAge: 65, fycRate: 16, marketingRate: 0, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8564' },
  { code: 'NATE', term: '20', minAge: 0, maxAge: 62, fycRate: 30, marketingRate: 0, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8564' },
  { code: '2AUE5', term: '2', minAge: 0, maxAge: 70, fycRate: 3, marketingRate: 1, cat: 'LIFE' , alias: ['2AUE'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/7062' },
  { code: 'NAUE', term: '6', minAge: 0, maxAge: 65, fycRate: 10, marketingRate: 0, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8527' },
  { code: 'NAUE', term: '10', minAge: 0, maxAge: 65, fycRate: 16, marketingRate: 0, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8527' },
  { code: '6AFTE3', term: '6', minAge: 0, maxAge: 99, fycRate: 5, marketingRate: 2, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/5221' },
  { code: 'STL6', term: '1', minAge: 0, maxAge: 99, fycRate: 0.5, marketingRate: 0.2, cat: 'LIFE' , alias: ['STL'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/5230' },
  { code: '6ATL', term: '6', minAge: 0, maxAge: 99, fycRate: 5, marketingRate: 2, cat: 'LIFE' , alias: ['ATL'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2836' },
  { code: '2AUL3', term: '2', minAge: 0, maxAge: 99, fycRate: 3, marketingRate: 1, cat: 'LIFE' , alias: ['AUL3'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2818' },
  { code: 'AYUDL', term: '6', minAge: 0, maxAge: 75, fycRate: 2, marketingRate: 0, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/5228' },
  { code: 'AYUDL', term: '10', minAge: 0, maxAge: 75, fycRate: 5, marketingRate: 0, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/5228' },
  { code: 'AYUPL3', term: '3', minAge: 0, maxAge: 75, fycRate: 9, marketingRate: 0, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/9941' },
  { code: 'AYUPL3', term: '3', minAge: 76, maxAge: 78, fycRate: 5, marketingRate: 0, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/9941' },
  { code: 'AYUPL3', term: '6', minAge: 0, maxAge: 75, fycRate: 16, marketingRate: 0, cat: 'LIFE' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/9941' },

  // --- 2. 固定型壽險 (FIXED) ---
  { code: '20NNPL', term: '20', minAge: 0, maxAge: 60, fycRate: 50, marketingRate: 0, cat: 'FIXED' , alias: ['NNPL'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2897' },
  { code: 'MPL3', term: '6', minAge: 0, maxAge: 29, fycRate: 8, marketingRate: 0, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/6206' },
  { code: 'MPL3', term: '6', minAge: 30, maxAge: 39, fycRate: 6, marketingRate: 0, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/6206' },
  { code: 'MPL3', term: '6', minAge: 0, maxAge: 29, fycRate: 5, marketingRate: 0, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/6206' },
  { code: 'MPL3', term: '10', minAge: 0, maxAge: 29, fycRate: 16, marketingRate: 0, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/6206' },
  { code: 'MPL3', term: '10', minAge: 30, maxAge: 39, fycRate: 12, marketingRate: 0, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/6206' },
  { code: 'MPL3', term: '10', minAge: 0, maxAge: 29, fycRate: 10, marketingRate: 0, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/6206' },
  { code: 'MPL3', term: '20', minAge: 0, maxAge: 29, fycRate: 30, marketingRate: 0, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/6206' },
  { code: 'MPL3', term: '20', minAge: 30, maxAge: 39, fycRate: 20, marketingRate: 0, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/6206' },
  { code: 'MPL3', term: '20', minAge: 0, maxAge: 29, fycRate: 15, marketingRate: 0, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/6206' },
  { code: 'AITPL', term: '6', minAge: 0, maxAge: 65, fycRate: 15, marketingRate: 2, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8103' },
  { code: 'AITPL', term: '6', minAge: 66, maxAge: 74, fycRate: 12, marketingRate: 1, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8103' },
  { code: 'AITPL', term: '10', minAge: 0, maxAge: 65, fycRate: 20, marketingRate: 5, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8103' },
  { code: 'AITPL', term: '10', minAge: 66, maxAge: 74, fycRate: 13, marketingRate: 5, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8103' },
  { code: 'AITPL', term: '20', minAge: 0, maxAge: 60, fycRate: 30, marketingRate: 10, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8103' },
  { code: 'NUPL5', term: '10', minAge: 0, maxAge: 65, fycRate: 25, marketingRate: 10, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3054' },
  { code: 'NUPL5', term: '20', minAge: 0, maxAge: 60, fycRate: 35, marketingRate: 20, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3054' },
  { code: 'NUPL5', term: '30', minAge: 0, maxAge: 50, fycRate: 40, marketingRate: 20, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3054' },
  { code: 'NTL2', term: '10', minAge: 15, maxAge: 60, fycRate: 20, marketingRate: 10, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2807' },
  { code: 'NTL2', term: '20', minAge: 15, maxAge: 55, fycRate: 30, marketingRate: 10, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2807' },
  { code: 'NTL2', term: '30', minAge: 15, maxAge: 45, fycRate: 40, marketingRate: 10, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2807' },
  { code: 'NTR2', term: '6', minAge: 15, maxAge: 60, fycRate: 10, marketingRate: 5, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2807' },
  { code: 'NTR2', term: '10', minAge: 15, maxAge: 60, fycRate: 20, marketingRate: 15, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2807' },
  { code: 'NTR2', term: '20', minAge: 15, maxAge: 55, fycRate: 40, marketingRate: 15, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2807' },
  { code: 'NTR2', term: '30', minAge: 15, maxAge: 45, fycRate: 40, marketingRate: 15, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2807' },
  { code: 'N1TR', term: '1', minAge: 15, maxAge: 60, fycRate: 10, marketingRate: 0, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2807' },
  { code: 'DMAL', term: '10', minAge: 15, maxAge: 60, fycRate: 30, marketingRate: 0, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3031' },
  { code: 'DMAL', term: '20', minAge: 15, maxAge: 50, fycRate: 45, marketingRate: 0, cat: 'FIXED' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3031' },

  // --- 3. 意外傷害 (PA) ---
  { code: 'SPA', term: '1', minAge: 0, maxAge: 99, fycRate: 15, marketingRate: 0, cat: 'PA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4240' },
  { code: 'SBB', term: '1', minAge: 15, maxAge: 75, fycRate: 20, marketingRate: 0, cat: 'PA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4240' },
  { code: 'SBBR', term: '1', minAge: 0, maxAge: 75, fycRate: 20, marketingRate: 0, cat: 'PA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4240' },
  { code: 'NAI', term: '1', minAge: 15, maxAge: 40, fycRate: 40, marketingRate: 10, cat: 'PA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4240' },
  { code: 'NAI', term: '1', minAge: 41, maxAge: 99, fycRate: 30, marketingRate: 5, cat: 'PA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4240' },
  { code: 'DHI', term: '1', minAge: 0, maxAge: 99, fycRate: 20, marketingRate: 0, cat: 'PA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4240' },
  { code: 'BBMR', term: '1', minAge: 0, maxAge: 99, fycRate: 20, marketingRate: 0, cat: 'PA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4240' },
  { code: 'PAMR', term: '1', minAge: 0, maxAge: 99, fycRate: 20, marketingRate: 0, cat: 'PA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4240' },
  { code: 'YPAR', term: '1', minAge: 0, maxAge: 99, fycRate: 20, marketingRate: 0, cat: 'PA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4240' },
  { code: 'KPA', term: '1', minAge: 0, maxAge: 15, fycRate: 20, marketingRate: 0, cat: 'PA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4240' },
  { code: 'KPAR', term: '1', minAge: 0, maxAge: 75, fycRate: 20, marketingRate: 0, cat: 'PA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4240' },
  { code: 'HWPA2', term: '20', minAge: 0, maxAge: 99, fycRate: 17, marketingRate: 0, cat: 'PA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4982' },

  // --- 4. 健康保險 - 住院手術 (HI) ---
  { code: '1HS', term: '1', minAge: 0, maxAge: 40, fycRate: 40, marketingRate: 10, cat: 'HI' , alias: ['HS'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/5208' },
  { code: '1HS', term: '1', minAge: 41, maxAge: 65, fycRate: 25, marketingRate: 10, cat: 'HI' , alias: ['HS'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/5208' },
  { code: '1HSCO', term: '1', minAge: 0, maxAge: 65, fycRate: 40, marketingRate: 10, cat: 'HI' , alias: ['HSCO'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/5208' },
  { code: '1HSCO', term: '1', minAge: 66, maxAge: 70, fycRate: 10, marketingRate: 0, cat: 'HI' , alias: ['HSCO'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/5208' },
  { code: '1HSD', term: '1', minAge: 0, maxAge: 40, fycRate: 40, marketingRate: 10, cat: 'HI' , alias: ['HSD'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/5208' },
  { code: '1HSD', term: '1', minAge: 41, maxAge: 65, fycRate: 25, marketingRate: 10, cat: 'HI' , alias: ['HSD'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/5208' },
  { code: '1NHI', term: '1', minAge: 0, maxAge: 65, fycRate: 40, marketingRate: 10, cat: 'HI' , alias: ['NHI'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/5208' },
  { code: '1NHI', term: '1', minAge: 66, maxAge: 75, fycRate: 10, marketingRate: 0, cat: 'HI' , alias: ['NHI'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/5208' },
  { code: '1HIR', term: '1', minAge: 0, maxAge: 65, fycRate: 40, marketingRate: 10, cat: 'HI' , alias: ['HIR'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/5208' },
  { code: '1HIR', term: '1', minAge: 66, maxAge: 75, fycRate: 10, marketingRate: 0, cat: 'HI' , alias: ['HIR'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/5208' },
  { code: '1SIR', term: '1', minAge: 0, maxAge: 65, fycRate: 40, marketingRate: 10, cat: 'HI' , alias: ['SIR'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/5208' },
  { code: '1SIR', term: '1', minAge: 66, maxAge: 75, fycRate: 10, marketingRate: 0, cat: 'HI' , alias: ['SIR'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/5208' },
  { code: 'TSIR3', term: '1', minAge: 0, maxAge: 60, fycRate: 20, marketingRate: 0, cat: 'HI' , alias: ['TSIR'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8465' },
  { code: 'TSIR3', term: '1', minAge: 61, maxAge: 65, fycRate: 10, marketingRate: 0, cat: 'HI' , alias: ['TSIR'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8465' },
  { code: 'HYPHI', term: '10', minAge: 0, maxAge: 45, fycRate: 23, marketingRate: 0, cat: 'HI' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2478' },
  { code: 'HYPHI', term: '10', minAge: 46, maxAge: 60, fycRate: 15, marketingRate: 0, cat: 'HI' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2478' },
  { code: 'STCB', term: '10', minAge: 0, maxAge: 99, fycRate: 25, marketingRate: 0, cat: 'HI' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2487' },
  { code: 'STCB', term: '20', minAge: 0, maxAge: 99, fycRate: 45, marketingRate: 0, cat: 'HI' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2487' },
  { code: 'HWHI', term: '10', minAge: 0, maxAge: 99, fycRate: 25, marketingRate: 0, cat: 'HI' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2472' },
  { code: 'HWHI', term: '20', minAge: 0, maxAge: 99, fycRate: 40, marketingRate: 0, cat: 'HI' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2472' },
  { code: 'HPSI2', term: '10', minAge: 0, maxAge: 49, fycRate: 25, marketingRate: 10, cat: 'HI' , alias: ['HPSI'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3641' },
  { code: 'HPSI2', term: '10', minAge: 50, maxAge: 55, fycRate: 20, marketingRate: 10, cat: 'HI' , alias: ['HPSI'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3641' },
  { code: 'HPSI2', term: '10', minAge: 56, maxAge: 70, fycRate: 15, marketingRate: 10, cat: 'HI' , alias: ['HPSI'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3641' },
  { code: 'HPSI2', term: '20', minAge: 0, maxAge: 49, fycRate: 40, marketingRate: 20, cat: 'HI' , alias: ['HPSI'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3641' },
  { code: 'HPSI2', term: '20', minAge: 50, maxAge: 55, fycRate: 35, marketingRate: 20, cat: 'HI' , alias: ['HPSI'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3641' },
  { code: 'HPSI2', term: '20', minAge: 56, maxAge: 65, fycRate: 30, marketingRate: 20, cat: 'HI' , alias: ['HPSI'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3641' },
  { code: 'HPHI2', term: '10', minAge: 0, maxAge: 99, fycRate: 25, marketingRate: 0, cat: 'HI' , alias: ['HPHI'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2484' },
  { code: 'HPHI2', term: '20', minAge: 0, maxAge: 99, fycRate: 40, marketingRate: 0, cat: 'HI' , alias: ['HPHI'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2484' },
  { code: 'HPHI2', term: '30', minAge: 0, maxAge: 99, fycRate: 45, marketingRate: 0, cat: 'HI' , alias: ['HPHI'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2484' },
  { code: 'HPCHI2', term: '10', minAge: 0, maxAge: 99, fycRate: 25, marketingRate: 0, cat: 'HI', alias: ['HPCHI'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2475' },
  { code: 'HPCHI2', term: '20', minAge: 0, maxAge: 99, fycRate: 40, marketingRate: 0, cat: 'HI' , alias: ['HPCHI'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2475' },
  { code: 'MSAE', term: '1', minAge: 0, maxAge: 99, fycRate: 20, marketingRate: 0, cat: 'HI' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2481' },
  { code: 'TDH', term: '1', minAge: 0, maxAge: 99, fycRate: 15, marketingRate: 20, cat: 'HI' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2490' },
  { code: 'SHI', term: '10', minAge: 55, maxAge: 80, fycRate: 20, marketingRate: 0, cat: 'HI' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/6588' },
  { code: 'SHI', term: '20', minAge: 55, maxAge: 70, fycRate: 30, marketingRate: 0, cat: 'HI' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/6588' },

  // --- 5. 健康保險 - 癌症重大 (CA) ---
  { code: 'HC', term: '10', minAge: 0, maxAge: 55, fycRate: 20, marketingRate: 0, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/9533' },
  { code: 'HC', term: '10', minAge: 56, maxAge: 70, fycRate: 15, marketingRate: 0, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/9533' },
  { code: 'HC', term: '20', minAge: 0, maxAge: 55, fycRate: 40, marketingRate: 0, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/9533' },
  { code: 'HC', term: '20', minAge: 56, maxAge: 65, fycRate: 30, marketingRate: 0, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/9533' },
  { code: 'HCAB2', term: '20', minAge: 0, maxAge: 55, fycRate: 40, marketingRate: 0, cat: 'CA', alias: ['HCAB'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3666' },
  { code: 'HCAB2', term: '20', minAge: 56, maxAge: 70, fycRate: 30, marketingRate: 0, cat: 'CA' , alias: ['HCAB'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3666' },
  { code: 'HCAR2', term: '20', minAge: 0, maxAge: 55, fycRate: 35, marketingRate: 0, cat: 'CA', alias: ['HCAR'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3666' },
  { code: 'HCAR2', term: '20', minAge: 56, maxAge: 70, fycRate: 25, marketingRate: 0, cat: 'CA' , alias: ['HCAR'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3666' },
  { code: 'TED', term: '10', minAge: 0, maxAge: 45, fycRate: 30, marketingRate: 3.5, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4923' },
  { code: 'TED', term: '10', minAge: 46, maxAge: 60, fycRate: 20, marketingRate: 3.5, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4923' },
  { code: 'TED', term: '20', minAge: 0, maxAge: 45, fycRate: 40, marketingRate: 5, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4923' },
  { code: 'TED', term: '20', minAge: 46, maxAge: 50, fycRate: 30, marketingRate: 5, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4923' },
  { code: 'TED35', term: '10', minAge: 16, maxAge: 45, fycRate: 25, marketingRate: 3.5, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8102' },
  { code: 'TED35', term: '10', minAge: 46, maxAge: 55, fycRate: 20, marketingRate: 3.5, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8102' },
  { code: 'TED35', term: '20', minAge: 16, maxAge: 45, fycRate: 35, marketingRate: 5, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8102' },
  { code: 'TED35', term: '20', minAge: 46, maxAge: 55, fycRate: 30, marketingRate: 5, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8102' },
  { code: '1TED', term: '1', minAge: 0, maxAge: 65, fycRate: 40, marketingRate: 10, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4923' },
  { code: 'ZDDR2', term: '20', minAge: 0, maxAge: 45, fycRate: 40, marketingRate: 0, cat: 'CA' , alias: ['ZDDR'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3675' },
  { code: 'ZDDR2', term: '20', minAge: 46, maxAge: 55, fycRate: 20, marketingRate: 0, cat: 'CA' , alias: ['ZDDR'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3675' },
  { code: 'ZDDR2', term: '20', minAge: 56, maxAge: 65, fycRate: 10, marketingRate: 0, cat: 'CA' , alias: ['ZDDR'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3675' },
  { code: 'HDD', term: '1', minAge: 0, maxAge: 45, fycRate: 40, marketingRate: 0, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3651' },
  { code: 'HDD', term: '1', minAge: 46, maxAge: 55, fycRate: 30, marketingRate: 0, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3651' },
  { code: 'SDLR2', term: '1', minAge: 0, maxAge: 49, fycRate: 40, marketingRate: 20, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3597' },
  { code: 'SDLR2', term: '1', minAge: 50, maxAge: 65, fycRate: 35, marketingRate: 20, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3597' },
  { code: '10TDD', term: '10', minAge: 20, maxAge: 60, fycRate: 15, marketingRate: 20, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3639' },
  { code: '10TDD', term: '10', minAge: 61, maxAge: 70, fycRate: 5, marketingRate: 0, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3639' },
  { code: '10TSDD', term: '10', minAge: 20, maxAge: 60, fycRate: 20, marketingRate: 20, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3645' },
  { code: '10TSDD', term: '10', minAge: 61, maxAge: 70, fycRate: 10, marketingRate: 10, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3645' },
  { code: 'HTBC', term: '20', minAge: 0, maxAge: 99, fycRate: 30, marketingRate: 0, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3662' },
  { code: 'HTSC', term: '20', minAge: 0, maxAge: 99, fycRate: 30, marketingRate: 0, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3662' },
  { code: 'URSD', term: '6', minAge: 0, maxAge: 45, fycRate: 25, marketingRate: 0, cat: 'CA' , alias: ['6URSDA' , '6URSDB'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3647' },
  { code: 'URSD', term: '6', minAge: 46, maxAge: 55, fycRate: 20, marketingRate: 0, cat: 'CA' , alias: ['6URSDA' , '6URSDB'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3647' },
  { code: 'URSD', term: '6', minAge: 56, maxAge: 65, fycRate: 10, marketingRate: 0, cat: 'CA' , alias: ['6URSDA' , '6URSDB'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3647' },
  { code: 'URSD', term: '20', minAge: 0, maxAge: 45, fycRate: 40, marketingRate: 0, cat: 'CA' , alias: ['20URSDA' , '20URSDB'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3647' },
  { code: 'URSD', term: '20', minAge: 46, maxAge: 55, fycRate: 35, marketingRate: 0, cat: 'CA' , alias: ['20URSDA' , '20URSDB'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3647' },
  { code: 'URSD', term: '20', minAge: 56, maxAge: 65, fycRate: 25, marketingRate: 0, cat: 'CA' , alias: ['20URSDA' , '20URSDB'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3647' },
  { code: '2TRSD', term: '2', minAge: 0, maxAge: 99, fycRate: 3, marketingRate: 7, cat: 'CA' , alias: ['TRSD'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3647' },
  { code: '2URSD2', term: '2', minAge: 0, maxAge: 99, fycRate: 3, marketingRate: 7, cat: 'CA' , alias: ['URSD2'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3025' },
  { code: 'UD', term: '6', minAge: 0, maxAge: 45, fycRate: 25, marketingRate: 0, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4980' },
  { code: 'UD', term: '6', minAge: 46, maxAge: 55, fycRate: 20, marketingRate: 0, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4980' },
  { code: 'UD', term: '6', minAge: 56, maxAge: 60, fycRate: 10, marketingRate: 0, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4980' },
  // 追加癌症險最後一頁五項 
  { code: '1RAS', term: '1', minAge: 0, maxAge: 99, fycRate: 20, marketingRate: 0, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3657' },
  { code: '1CGT', term: '1', minAge: 0, maxAge: 99, fycRate: 20, marketingRate: 0, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3657' },
  { code: '1STT', term: '1', minAge: 0, maxAge: 99, fycRate: 20, marketingRate: 0, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3657' },
  { code: '1SCT', term: '1', minAge: 0, maxAge: 99, fycRate: 20, marketingRate: 0, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3657' },
  { code: '1CPT', term: '1', minAge: 0, maxAge: 99, fycRate: 20, marketingRate: 0, cat: 'CA' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3657' },

  // --- 6. 長照險商品 (LTC) ---
  { code: '1LTC', term: '1', minAge: 0, maxAge: 99, fycRate: 40, marketingRate: 10, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2857' },
  { code: '10TLTC', term: '10', minAge: 0, maxAge: 99, fycRate: 30, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4098' },
  { code: 'FLTC', term: '10', minAge: 15, maxAge: 70, fycRate: 18, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4086' },
  { code: 'FLTC', term: '20', minAge: 15, maxAge: 39, fycRate: 30, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4086' },
  { code: 'FLTC', term: '20', minAge: 40, maxAge: 60, fycRate: 24, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4086' },
  { code: 'FLTC', term: '30', minAge: 15, maxAge: 39, fycRate: 32, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4086' },
  { code: 'FLTC', term: '30', minAge: 40, maxAge: 50, fycRate: 28, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4086' },
  { code: 'HTLTC', term: '10', minAge: 15, maxAge: 65, fycRate: 22, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2890' },
  { code: 'HTLTC', term: '20', minAge: 15, maxAge: 39, fycRate: 37, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2890' },
  { code: 'HTLTC', term: '20', minAge: 40, maxAge: 60, fycRate: 30, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2890' },
  { code: 'HTLTC', term: '30', minAge: 15, maxAge: 39, fycRate: 42, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2890' },
  { code: 'HTLTC', term: '30', minAge: 40, maxAge: 50, fycRate: 35, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2890' },
  { code: 'HRLTC', term: '10', minAge: 15, maxAge: 70, fycRate: 20, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/6706' },
  { code: 'HRLTC', term: '20', minAge: 15, maxAge: 39, fycRate: 35, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/6706' },
  { code: 'HRLTC', term: '20', minAge: 40, maxAge: 60, fycRate: 28, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/6706' },
  { code: 'HRLTC', term: '30', minAge: 15, maxAge: 39, fycRate: 40, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/6706' },
  { code: 'HRLTC', term: '30', minAge: 40, maxAge: 50, fycRate: 33, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/6706' },
  { code: 'HPLTC', term: '10', minAge: 15, maxAge: 49, fycRate: 22, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2875' },
  { code: 'HPLTC', term: '10', minAge: 50, maxAge: 65, fycRate: 17, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2875' },
  { code: 'HPLTC', term: '20', minAge: 15, maxAge: 39, fycRate: 37, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2875' },
  { code: 'HPLTC', term: '20', minAge: 40, maxAge: 60, fycRate: 30, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2875' },
  { code: 'HLTC', term: '10', minAge: 15, maxAge: 49, fycRate: 22, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2887' },
  { code: 'HLTC', term: '10', minAge: 50, maxAge: 65, fycRate: 17, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2887' },
  { code: 'HLTC', term: '20', minAge: 15, maxAge: 39, fycRate: 37, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2887' },
  { code: 'HLTC', term: '20', minAge: 40, maxAge: 60, fycRate: 30, marketingRate: 0, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/2887' },
  { code: 'KRLTC', term: '10', minAge: 0, maxAge: 15, fycRate: 20, marketingRate: 10, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/9564' },
  { code: 'KRLTC', term: '20', minAge: 0, maxAge: 15, fycRate: 35, marketingRate: 10, cat: 'LTC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/9564' },

  // --- 7. 特定議題 (TOPIC) ---
  { code: 'LCA', term: '20', minAge: 0, maxAge: 99, fycRate: 40, marketingRate: 0, cat: 'TOPIC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3598' },
  { code: 'MMC', term: '1', minAge: 18, maxAge: 43, fycRate: 40, marketingRate: 0, cat: 'TOPIC', alias: ['MOMMY CARE'] , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/4984' },
  { code: 'DMA', term: '10', minAge: 0, maxAge: 99, fycRate: 30, marketingRate: 0, cat: 'TOPIC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/10339' },
  { code: 'DMA', term: '20', minAge: 0, maxAge: 99, fycRate: 45, marketingRate: 0, cat: 'TOPIC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/10339' },
  { code: 'TKI', term: '15', minAge: 20, maxAge: 50, fycRate: 20, marketingRate: 0, cat: 'TOPIC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3248' },
  { code: 'HLD', term: '10', minAge: 20, maxAge: 49, fycRate: 25, marketingRate: 10, cat: 'TOPIC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8464' },
  { code: 'HLD', term: '10', minAge: 50, maxAge: 60, fycRate: 15, marketingRate: 10, cat: 'TOPIC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8464' },
  { code: 'HLD', term: '20', minAge: 20, maxAge: 49, fycRate: 30, marketingRate: 20, cat: 'TOPIC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8464' },
  { code: 'HLD', term: '20', minAge: 50, maxAge: 60, fycRate: 20, marketingRate: 20, cat: 'TOPIC' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/8464' },

  // --- 8. 投資型/年金 (INVEST) ---
  { code: 'BVA2', term: '1', minAge: 0, maxAge: 99, fycRate: 0.5, marketingRate: 3, cat: 'INVEST' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/5737' },
  { code: 'RVLSP', term: '1', minAge: 0, maxAge: 99, fycRate: 0.5, marketingRate: 3, cat: 'INVEST' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/7644' },
  { code: 'AUISA2', term: '1', minAge: 0, maxAge: 99, fycRate: 0.5, marketingRate: 0.5, cat: 'INVEST' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3084' },
  { code: 'PISA3', term: '1', minAge: 0, maxAge: 99, fycRate: 0.5, marketingRate: 0, cat: 'INVEST' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/3076' },
  { code: 'VADBG', term: '1', minAge: 0, maxAge: 99, fycRate: 2.5, marketingRate: 0, cat: 'INVEST' , dmUrl: 'https://www.nanshanlife.com.tw/nanshanlife/portal-api/File/9252' },
];